# Generated by Django 6.0.2 on 2026-02-24 09:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, help_text='Auto-generated: PO-YYYY-XXXX', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('received', 'Received'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(help_text='Warehouse receiving the shipment', limit_choices_to={'location_type__in': ['warehouse', 'distribution']}, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_purchase_orders', to='network.location')),
                ('supplier', models.ForeignKey(limit_choices_to={'location_type': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='network.location')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('received_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Received'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('received_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.purchaseorder')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_pos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order Receipt',
                'verbose_name_plural': 'Purchase Order Receipts',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('condition', models.CharField(choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('rejected', 'Rejected')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='orders.purchaseorderitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaseorderreceipt')),
            ],
            options={
                'verbose_name': 'Receipt Item',
                'verbose_name_plural': 'Receipt Items',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('partially_fulfilled', 'Partially Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(limit_choices_to={'location_type': 'store'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='network.location')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_fulfilled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='inventory.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Order Item',
                'verbose_name_plural': 'Sales Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_backordered', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expected_fulfillment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorders', to='network.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorders', to='inventory.product')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='orders.salesorderitem')),
            ],
            options={
                'verbose_name': 'Back Order',
                'verbose_name_plural': 'Back Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('actual_arrival_date', models.DateField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='network.location')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='network.shippingroute')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='network.location')),
            ],
            options={
                'verbose_name': 'Transfer Order',
                'verbose_name_plural': 'Transfer Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('shipped_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('received', 'Received')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.product')),
                ('transfer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.transferorder')),
            ],
            options={
                'verbose_name': 'Transfer Order Item',
                'verbose_name_plural': 'Transfer Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='orders_purc_po_numb_030b57_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='orders_purc_status_f227fe_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='orders_purc_supplie_79a335_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['-created_at'], name='orders_purc_created_142ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_number'], name='orders_sale_order_n_6ce2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='orders_sale_status_b5a0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['store'], name='orders_sale_store_i_340f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['-order_date'], name='orders_sale_order_d_07cf97_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['status'], name='orders_back_status_1d6ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['product', 'location'], name='orders_back_product_0d3db2_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['transfer_number'], name='orders_tran_transfe_111354_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['status'], name='orders_tran_status_913710_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['from_location', 'to_location'], name='orders_tran_from_lo_910645_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['-created_at'], name='orders_tran_created_4da644_idx'),
        ),
    ]
