# Generated by Django 4.2.10 on 2026-02-19 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location_type', models.CharField(choices=[('supplier', 'Supplier'), ('warehouse', 'Warehouse'), ('distribution', 'Distribution Center'), ('store', 'Store')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum storage capacity (optional)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('manager_name', models.CharField(blank=True, max_length=200)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('manager_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['location_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_lead_time_days', models.IntegerField(help_text='Average shipping time in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('shipping_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit shipped', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='network.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='network.location')),
            ],
            options={
                'verbose_name': 'Shipping Route',
                'verbose_name_plural': 'Shipping Routes',
                'ordering': ['from_location', 'to_location'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='network_loc_locatio_9aa44b_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active'], name='network_loc_is_acti_75f9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingroute',
            index=models.Index(fields=['from_location', 'to_location'], name='network_shi_from_lo_5f81d7_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingroute',
            index=models.Index(fields=['is_active'], name='network_shi_is_acti_29815b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingroute',
            unique_together={('from_location', 'to_location')},
        ),
    ]
