# Generated by Django 4.2.10 on 2026-02-19 17:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_sold', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demand History',
                'verbose_name_plural': 'Demand History',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField(default=0, help_text='Physical quantity in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_reserved', models.IntegerField(default=0, help_text='Quantity allocated for pending orders', validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_incoming', models.IntegerField(default=0, help_text='Quantity expected from POs/transfers', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_point', models.IntegerField(default=0, help_text='Trigger reorder when stock falls below this', validators=[django.core.validators.MinValueValidator(0)])),
                ('safety_stock', models.IntegerField(default=0, help_text='Buffer stock to prevent stockouts', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_stock', models.IntegerField(blank=True, help_text='Maximum stock level (optional)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_counted_at', models.DateTimeField(blank=True, help_text='Last physical inventory count', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Level',
                'verbose_name_plural': 'Inventory Levels',
                'ordering': ['location', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit - unique product identifier', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(default='pieces', help_text='e.g., pieces, kg, liters, boxes', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dimensions_cm', models.CharField(blank=True, help_text='Format: LxWxH (e.g., 30x20x10)', max_length=50)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sale'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Inventory Adjustment'), ('return', 'Return'), ('damage', 'Damage/Loss')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('reference_type', models.CharField(blank=True, help_text='e.g., PurchaseOrder, TransferOrder, SalesOrder', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the source document', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='network.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReorderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField()),
                ('reorder_point', models.IntegerField()),
                ('suggested_order_quantity', models.IntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('ordered', 'Order Placed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_alerts', to='network.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_alerts', to='inventory.product')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_reorders', to='network.location')),
            ],
            options={
                'verbose_name': 'Reorder Alert',
                'verbose_name_plural': 'Reorder Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, help_text="Supplier's internal product code", max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_time_days', models.IntegerField(help_text='Days from order to delivery', validators=[django.core.validators.MinValueValidator(1)])),
                ('minimum_order_quantity', models.IntegerField(default=1, help_text='Minimum quantity that can be ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred supplier for this product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='inventory.product')),
                ('supplier', models.ForeignKey(limit_choices_to={'location_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='network.location')),
            ],
            options={
                'verbose_name': 'Product Supplier',
                'verbose_name_plural': 'Product Suppliers',
                'ordering': ['-is_preferred', 'unit_cost'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='inventory_p_is_acti_47a270_idx'),
        ),
        migrations.AddField(
            model_name='inventorylevel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='network.location'),
        ),
        migrations.AddField(
            model_name='inventorylevel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='demandhistory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_history', to='network.location'),
        ),
        migrations.AddField(
            model_name='demandhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_history', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'location'], name='inventory_s_product_86d701_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-created_at'], name='inventory_s_created_2ec5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['status'], name='inventory_r_status_938607_idx'),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['product', 'location'], name='inventory_r_product_339aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['-created_at'], name='inventory_r_created_ab13c7_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['product', 'supplier'], name='inventory_p_product_d9f552_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['is_preferred'], name='inventory_p_is_pref_0bf8bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsupplier',
            unique_together={('product', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='inventorylevel',
            index=models.Index(fields=['product', 'location'], name='inventory_i_product_75453d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylevel',
            index=models.Index(fields=['quantity_on_hand'], name='inventory_i_quantit_144709_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylevel',
            index=models.Index(fields=['location'], name='inventory_i_locatio_ca769d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorylevel',
            unique_together={('product', 'location')},
        ),
        migrations.AddIndex(
            model_name='demandhistory',
            index=models.Index(fields=['product', 'location', '-date'], name='inventory_d_product_d1c176_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='demandhistory',
            unique_together={('product', 'location', 'date')},
        ),
    ]
